import { INTERNAL_EVENTS, MAX_STOP_CONTINUATIONS, type EventId } from "./flow";

// Editorial situations to replay. Routes and state changes come from the reducer.
export const TRACES = [
  { name: "Several items at once", description: "Four edits enter one agent's virtual round. Three source readings start; the fourth edit waits. Three prepared items occupy Jev slots while a fourth waits for a result. One finding is already pending advice and another remains in the Jev results queue. At the finish-decision deadline, the policy batches both, cancels work still running, and keeps the virtual round open for repair.", events: [
    "EditObserved", "EditObserved", "EditObserved", "EditObserved",
    "ReviewUnitPrepared", "ReviewUnitPrepared", "ReviewUnitPrepared", "ReviewUnitPrepared",
    "JevFindingReceived", "FindingRetained", "JevFindingReceived", "StopHookFired",
    "FinishDecisionDeadlineReached", "StopHookFired",
  ] },
  { name: "Send advice after a tool", description: "The after-tool hook asks for advice. Hapsland selects a finding and writes the hook response. The agent runtime controls further use.", events: [
    "EditObserved", "ReviewUnitPrepared", "JevFindingReceived", "FindingRetained", "BackgroundHookFired",
    "AdviceLeasedByBackground", "HostOutputSubmitted",
  ] },
  { name: "Reoffer during a finish attempt", description: "Hapsland has reserved advice for background output when the runtime calls its Stop hook. The background write completes during that open hook call; Hapsland selects the same advice for the finish decision.", events: [
    "EditObserved", "ReviewUnitPrepared", "JevFindingReceived", "FindingRetained", "BackgroundHookFired",
    "AdviceLeasedByBackground", "StopHookFired", "HostOutputSubmitted",
  ] },
  { name: "Finish-decision wait receives advice", description: "The runtime calls its Stop hook while Jev is running. Hapsland holds that call open; a finding arrives and the reducer chooses a continue-with-advice response before the deadline. The adapter's actual write is outside this model.", events: [
    "EditObserved", "ReviewUnitPrepared", "StopHookFired", "JevFindingReceived",
  ] },
  { name: "Clear result", description: "A Jev result with no finding updates the review status. There is no advice to send.", events: [
    "EditObserved", "ReviewUnitPrepared", "JevClearReceived", "ClearRecorded",
  ] },
  { name: "Jev unavailable", description: "A failed Jev request records a failed review. It does not establish that the source has no finding.", events: [
    "EditObserved", "ReviewUnitPrepared", "JevUnavailable", "UnavailableRecorded",
  ] },
  { name: "Edit opens a virtual round", description: "An agent can enter through an attributed edit without a user-prompt hook. The runtime adapter handles root and subagent details.", events: [
    "EditObserved", "ReviewUnitPrepared", "JevFindingReceived", "FindingRetained", "StopHookFired", "StopHookFired",
  ] },
  { name: "Finish-decision wait expires", description: "Jev has not replied by the finish-decision deadline. Hapsland returns allow from the runtime's Stop hook. All live virtual-round data is removed, including the running request. A fresh edit can open another virtual round.", events: [
    "EditObserved", "ReviewUnitPrepared", "StopHookFired", "FinishDecisionDeadlineReached", "EditObserved",
  ] },
  { name: `${MAX_STOP_CONTINUATIONS} continuation requests`, description: `Each repair can be reviewed again. ${MAX_STOP_CONTINUATIONS} block responses through the runtime's Stop hook request continuation in the same virtual round; the next finish attempt must receive allow.`, events: [
    ...Array.from({ length: MAX_STOP_CONTINUATIONS }, () => [
      "EditObserved", "ReviewUnitPrepared", "JevFindingReceived", "FindingRetained", "StopHookFired",
    ] as const).flat(), "StopHookFired",
  ] },
] as const satisfies ReadonlyArray<{ readonly name: string; readonly description: string; readonly events: ReadonlyArray<EventId> }>;

// Internal starts are generated by the reducer; every external event has an accepted scenario.
type CoveredEvent = (typeof TRACES)[number]["events"][number];
type InternalEvent = (typeof INTERNAL_EVENTS)[number];
const completeCoverage: Exclude<EventId, CoveredEvent | InternalEvent> extends never ? true : never = true;
void completeCoverage;
