// THROWAWAY: observed replay projection, not an exhaustive transition graph.
import assert from "node:assert/strict"
import { readFileSync, writeFileSync } from "node:fs"
import { command, initial, safeObservation, type Event, type Model } from "./domain.ts"
import { reduce } from "./reducer.ts"
import { runScenarios } from "./scenarios.ts"
const phaseLabel = (phase: Model["phase"]) => (phase === "Select" ? "Select Agents" : phase)
const changed = new Set<string>()
const ignored = new Set<string>()
const reports: string[] = []
function label(before: Model, after: Model, event: Event): string {
  if (event.revision !== before.revision) return "stale revision"
  const action = safeObservation(before, event).action
  switch (action.kind) {
    case "select":
      return action.hosts.length ? "select agents" : "empty selection (headless only)"
    case "approve":
      return action.yes
        ? "approve"
        : before.phase === "Hooks"
          ? `decline; ${after.phase === "Hooks" ? "more agents" : "last agent"}`
          : "decline"
    case "destination":
      return `destination ${action.destination}`
    case "observed": {
      if (action.commandId !== before.revision) return "wrong command ID"
      const suffix = before.phase === "Applying" ? (after.phase === "Hooks" ? "; more agents" : "; last agent") : ""
      return `owner: ${action.outcome}${suffix}`
    }
    default:
      return action.kind
  }
}
await runScenarios(async (name, source, drive) => {
  let model = initial(source)
  const trace: string[] = []
  await drive(async (event) => {
    const before = model
    model = reduce(before, event)
    const unchanged = JSON.stringify(model) === JSON.stringify(before)
    const text = label(before, model, event)
    const issued = unchanged ? undefined : command(model)
    const edge = `  ${before.phase} -->|"${text}${issued ? ` / emit ${issued.type}` : ""}"| ${model.phase}`
    ;(unchanged ? ignored : changed).add(edge)
    trace.push(
      `| ${trace.length + 1} | ${phaseLabel(before.phase)} → ${phaseLabel(model.phase)} | ${text} | ${event.revision} → ${model.revision} | ${issued ? `${issued.type} #${issued.id}` : "—"} |`
    )
    return model
  }, model)
  reports.push(
    `### ${name}\n\nInitial context: source **${source}**, phase **Select Agents**, revision **0**, no selected agents or prior results.\n\n| Step | Observed phases | Event | Revision | Newly issued command |\n| --- | --- | --- | --- | --- |\n${trace.join("\n")}`
  )
})
const coverage =
  "This diagram shows transitions observed by the declared scenario replays through the current reducer. Regeneration keeps it current for those scenarios; it does not establish exhaustive coverage. New states, guards or context-dependent branches may remain absent until scenarios exercise them. Diagram freshness does not establish behavioral correctness."
const markdown = `# Setup reducer replay diagram

**Purpose:** Show observed setup transitions and correlated commands from executable prototype scenarios.
**Status:** Generated throwaway prototype evidence.
**Authority:** Bounded replay evidence; not an accepted product contract or proof of all legal behavior.
**Expected use:** Preview this Markdown with Mermaid support alongside the console prototype; regenerate explicitly after reducer or scenario changes.
**Lifecycle:** Delete at the setup-interaction design acceptance milestone; consolidate adopted generator behavior and coverage limits into the production generator's owner documentation, and architectural decisions into an ADR. Update inbound links before deleting.

> ${coverage}

Generated by \`npm run diagram:write\`; verified without rewriting by \`npm run diagram:check\`. Source: [scenario drivers](scenarios.ts) replayed through the [actual reducer](reducer.ts). Independent assertions inside the drivers still check behavior.

## Keyboard navigation

Escape dispatches the same Back event as the Back button on Hooks, Credential, SaveApproval and CheckApproval menus. At the first selection dialog Escape exits; hidden key entry keeps its existing cancellation/exit behavior.

Select Agents chooses agents. Hooks previews and asks approval for one agent’s hook changes. Applying executes those approved hook changes (simulated here), then returns to Hooks for another agent or proceeds to Credential after the last agent. Approve is an event, not a phase or a proof. Back from Hooks returns to Select Agents without undoing earlier applied results.

## Observed state-changing transitions

\`emit\` means the resulting state exposes a command to the interpreter, not that a real operation ran. Key entry uses Prompt.Hidden within the synthetic save interpreter; it is not a reducer phase and is not depicted as one.

\`\`\`mermaid
flowchart TD
  Select["Select Agents"]
${[...changed].sort().join("\n")}
\`\`\`

## Observed ignored inputs

These self-loops preserve the entire model and issue no new command. An already-pending command may remain present. This companion view keeps ignored inputs out of the main flow.

\`\`\`mermaid
flowchart TD
  Select["Select Agents"]
${[...ignored].sort().join("\n")}
\`\`\`

## Replay details

Revisions and command IDs are retained for correlation; credential values, owner payloads and approval digests are excluded. Branch labels such as “more agents” describe the observed resulting phase, not an inferred exhaustive guard.

${reports.join("\n\n")}
`
const file = new URL("./diagram.md", import.meta.url)
if (process.argv.includes("--write")) writeFileSync(file, markdown)
else assert.equal(readFileSync(file, "utf8"), markdown, "diagram.md is stale; run npm run diagram:write")
console.log(
  JSON.stringify({
    scenarios: reports.length,
    transitions: changed.size,
    ignored: ignored.size,
    freshness: "passed",
    realOperations: 0
  })
)
