// THROWAWAY: replay the actual rules workflow; never serialize plans or digests.
import assert from "node:assert/strict"
import { readFileSync, writeFileSync } from "node:fs"
import { Effect } from "effect"
import { runRules, type RulesTransition } from "./rules-flow.ts"
import { createRulesOwner, type OwnerOutcome } from "./rules-owner.ts"
import type { RuleAction } from "./rules-model.ts"
import { scriptedInteraction, type ScriptStep } from "./scripted-interaction.ts"
const choose = (index: number): ScriptStep => ({ kind: "choose", index })
const confirm = (line: string): ScriptStep => ({ kind: "confirm", line })
const edges = new Set<string>()
const reports: string[] = []
async function replay(
  name: string,
  steps: ScriptStep[],
  expected: string,
  writes: number,
  action: RuleAction = "create",
  outcome: OwnerOutcome = "applied"
) {
  const script = scriptedInteraction(steps)
  const owner = createRulesOwner(outcome)
  const rows: string[] = []
  const observe = ({ before, event, after }: RulesTransition) =>
    Effect.sync(() => {
      const action = event.action
      const label =
        action.kind === "scope"
          ? `scope ${action.scope}`
          : action.kind === "approve"
            ? action.yes
              ? "approve y"
              : "decline"
            : action.kind === "observed"
              ? `owner ${action.outcome}`
              : action.kind
      edges.add(`  ${before.phase} -->|"${label}"| ${after.phase}`)
      const commandId = "commandId" in action ? action.commandId : "—"
      rows.push(
        `| ${rows.length + 1} | ${before.phase} → ${after.phase} | ${label} | ${event.revision} → ${after.revision} | ${commandId} |`
      )
    })
  const model = await Effect.runPromise(runRules(script.interaction, owner, action, observe))
  assert.equal(model.outcome ?? model.phase, expected)
  assert.equal(owner.writes(), writes)
  assert.equal(script.remaining(), 0)
  reports.push(
    `### ${name}\n\nInitial state: Scope, revision 0, action ${action}; fresh synthetic owner (${outcome}).\n\n| Step | Phases | Event | Revision | Observed command ID |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}`
  )
}
for (const action of ["create", "connect", "enable", "disable"] as const)
  for (const scope of [0, 1])
    await replay(
      `${action}-${scope ? "personal" : "project"}`,
      [choose(scope), choose(0), confirm("y")],
      "applied",
      1,
      action
    )
await replay("default-decline", [choose(0), choose(0), confirm("")], "declined", 0)
await replay(
  "back-and-change-scope",
  [choose(0), { kind: "back" }, choose(1), choose(0), { kind: "back" }, choose(0), confirm("y")],
  "applied",
  1
)
await replay(
  "changed-proposal-fresh-consent",
  [choose(0), choose(0), confirm("y"), choose(0), confirm("y")],
  "applied",
  1,
  "enable",
  "stale"
)
for (const ending of ["exit", "eof"] as const)
  for (const prefix of [[], [choose(0)], [choose(0), choose(0)]])
    await replay(`${ending}-after-${prefix.length}-choices`, [...prefix, { kind: ending }], "Cancelled", 0)
for (const outcome of ["failed", "partial"] as const)
  await replay(
    outcome,
    [choose(0), choose(0), confirm("y")],
    outcome,
    outcome === "partial" ? 1 : 0,
    "disable",
    outcome
  )
const markdown = `# Rules workflow replay diagram

**Purpose:** Show observed rules interaction transitions from executable workflow replays.
**Status:** Generated throwaway prototype evidence.
**Authority:** Bounded synthetic replay evidence, not a production contract or exhaustive graph.
**Expected use:** Inspect beside the rules console demo; regenerate after workflow or scenario changes.
**Lifecycle:** At #244 prototype acceptance, consolidate adopted generation conventions into the production workflow documentation and architecture ADR, update inbound links, and delete this temporary artifact.

Generated by \`npm run diagram:write\`; checked without rewriting by \`npm run diagram:check\`. Replays execute [the rules workflow](rules-flow.ts) through its actual [reducer](rules-model.ts) and injected synthetic owner. Independent assertions check observed outcome, write count and script exhaustion.

## Observed transitions

\`\`\`mermaid
flowchart TD
${[...edges].sort().join("\n")}
\`\`\`

Scope selection does not write. Previewing obtains an owner proposal; Applying executes an explicitly approved proposal. A stale proposal returns to preview generation and requires fresh consent. Escape equals Back where offered; at Scope it exits. EOF exits the input session. Applying waits for an observed owner result rather than implying rollback. Full-line confirmation approves only trimmed, case-insensitive **y**.

## Coverage limits

Only the declared scenario paths appear. This graph is neither exhaustive nor proof of correctness. Live focus, terminal rendering and hidden input are not modeled here. Freshness checks output consistency only. Tables retain revisions and command IDs; they exclude plans, approval digests, keys, raw owner payloads and confirmation text.

## Replay details

${reports.join("\n\n")}
`
const file = new URL("./rules-diagram.md", import.meta.url)
if (process.argv.includes("--write")) writeFileSync(file, markdown)
else assert.equal(readFileSync(file, "utf8"), markdown, "rules-diagram.md is stale; run npm run diagram:write")
console.log(
  JSON.stringify({ scenarios: reports.length, transitions: edges.size, freshness: "passed", realOperations: 0 })
)
