// Prototype: generate separate Markdown artifacts from actual workflow replays.
import assert from "node:assert/strict"
import { readFileSync, writeFileSync } from "node:fs"
import { runWorkflowScenarios, type Workflow, type ScenarioReplay } from "./workflow-scenarios.ts"
const collected: Record<Workflow, ScenarioReplay[]> = { update: [], maintenance: [], login: [], verification: [] }
const qualification = await runWorkflowScenarios((scenario) => collected[scenario.workflow].push(scenario))
for (const [workflow, scenarios] of Object.entries(collected)) {
  const changed = new Set<string>(),
    ignored = new Set<string>()
  const tables = scenarios.map(({ name, trace }) => {
    for (const step of trace)
      (step.from === step.to && step.revision === step.nextRevision ? ignored : changed).add(
        `  ${step.from} -->|"${step.event}"| ${step.to}`
      )
    return `### ${name}\n\nFresh ${workflow} model at revision 0 and a scenario-specific synthetic owner.\n\n| Step | Phases | Event | Revision | Observed command ID |\n| --- | --- | --- | --- | --- |\n${trace.map((step, index) => `| ${index + 1} | ${step.from} → ${step.to} | ${step.event} | ${step.revision} → ${step.nextRevision} | ${step.commandId ?? "—"} |`).join("\n")}`
  })
  const markdown = `# ${workflow[0]!.toUpperCase() + workflow.slice(1)} workflow replay diagram

**Purpose:** Show observed ${workflow} interaction transitions from named executable prototype scenarios.
**Status:** Generated prototype evidence; production owner integration is pending.
**Authority:** Bounded synthetic replay evidence, not an accepted product contract or exhaustive proof.
**Expected use:** Preview alongside the console demo and scenario assertions; explicitly regenerate after model or scenario changes.
**Lifecycle:** After #244 production integration and validation, consolidate useful decisions, generator conventions and tests into their production owners and ADR; update inbound links and delete this prototype artifact with the other #244 prototypes.

Generated by \`npm run diagram:write\`; checked without rewriting by \`npm run diagram:check\`. Source: [named scenarios](workflow-scenarios.ts) through the [actual ${workflow} model/interpreter](${workflow}-flow.ts). The generator does not maintain expected edges. Independent assertions check behavior and authorized effects separately from freshness.

## Observed state-changing transitions

\`\`\`mermaid
flowchart TD
${[...changed].sort().join("\n")}
\`\`\`

## Coverage and safety limits

These ${scenarios.length} declared replays cover observed paths only. Missing branches, rendering, focus, physical terminal behavior and arbitrary scheduling remain outside this graph. Freshness is not exhaustive coverage or correctness. Captured keys, raw owner/provider payloads, approval digests, credential generation values and input text are excluded. Tables retain only phases, bounded event labels, revisions and command IDs. Capturing/Saving are safe control phases: no key is stored in the model or event. Direct/headless CLI exceptions have no invented dialog graphs.
${ignored.size ? `\nObserved ignored inputs:\n\n\`\`\`mermaid\nflowchart TD\n${[...ignored].sort().join("\n")}\n\`\`\`\n` : ""}
## Replay details

${tables.join("\n\n")}
`
  const file = new URL(`./${workflow}-diagram.md`, import.meta.url)
  if (process.argv.includes("--write")) writeFileSync(file, markdown)
  else assert.equal(readFileSync(file, "utf8"), markdown, `${workflow} diagram is stale; run npm run diagram:write`)
}
console.log(JSON.stringify({ ...qualification, diagrams: Object.keys(collected), freshness: "passed" }))
