-- Generated by motion-arithmetic.mjs from the actual owner definitions and accepted laws.
import Std.Tactic.BVDecide
set_option linter.unusedSimpArgs false
abbrev U32 := BitVec 32
structure Point where
  x : U32
  y : U32
  deriving DecidableEq
def min32 (a b : U32) : U32 := if a.ult b then a else b
def max32 (a b : U32) : U32 := if a.ult b then b else a
def eq32 (a b : U32) : Bool := a == b


def Map.distance_order (a : U32) (b : U32) (up : Bool) : U32 := (if up then (b - a) else (a - b))

def Map.distance (a : U32) (b : U32) : U32 := (Map.distance_order a b (BitVec.ule a b))

def Map.travel_coordinate_order (a : U32) (b : U32) (pixels : U32) (up : Bool) : U32 := (if up then (a + (min32 pixels (b - a))) else (a - (min32 pixels (a - b))))

def Map.travel_coordinate (a : U32) (b : U32) (pixels : U32) : U32 := (Map.travel_coordinate_order a b pixels (BitVec.ule a b))

def Motion.travel (start : Point) (target : Point) : Point := (if (eq32 (Point.x start) (Point.x target)) then (Point.mk (Point.x start) (Map.travel_coordinate (Point.y start) (Point.y target) (4 : U32))) else (Point.mk (Map.travel_coordinate (Point.x start) (Point.x target) (4 : U32)) (Point.y start)))

-- Supporting proofs, inserted after mechanically lowered owner definitions.
-- The two conversion lemmas prove non-overflow, not assume it.
namespace MotionFacts

theorem coordinate_up (a b p : U32) (h : a.toNat ≤ b.toNat) :
    (Map.travel_coordinate a b p).toNat = a.toNat + min p.toNat (b.toNat - a.toNat) := by
  unfold Map.travel_coordinate Map.travel_coordinate_order min32
  simp only [BitVec.ule_eq_decide, BitVec.ult_eq_decide, decide_eq_true_eq, ite_eq_left h]
  have sub := BitVec.toNat_sub_of_le (x := b) (y := a) h
  simp only [sub]
  split
  · rename_i hp
    rw [BitVec.toNat_add_of_lt (by have := b.isLt; omega)]
    simp only [Nat.min_def]
    split <;> omega
  · rename_i hp
    rw [BitVec.toNat_add_of_lt (by have := b.isLt; omega), sub]
    simp only [Nat.min_def]
    split <;> omega

theorem coordinate_down (a b p : U32) (h : ¬a.toNat ≤ b.toNat) :
    (Map.travel_coordinate a b p).toNat = a.toNat - min p.toNat (a.toNat - b.toNat) := by
  unfold Map.travel_coordinate Map.travel_coordinate_order min32
  simp only [BitVec.ule_eq_decide, BitVec.ult_eq_decide, decide_eq_true_eq, ite_eq_right h]
  have sub := BitVec.toNat_sub_of_le (x := a) (y := b) (by change b.toNat ≤ a.toNat; omega)
  simp only [sub]
  split
  · rename_i hp
    rw [BitVec.toNat_sub_of_le (by change _ ≤ a.toNat; omega)]
    simp only [Nat.min_def]
    split <;> omega
  · rename_i hp
    rw [BitVec.toNat_sub_of_le (by change _ ≤ a.toNat; omega), sub]
    simp only [Nat.min_def]
    split <;> omega

theorem coordinate_toNat (a b p : U32) :
    (Map.travel_coordinate a b p).toNat =
      if a.toNat ≤ b.toNat then a.toNat + min p.toNat (b.toNat - a.toNat)
      else a.toNat - min p.toNat (a.toNat - b.toNat) := by
  by_cases h : a.toNat ≤ b.toNat
  · rw [ite_eq_left h]
    exact coordinate_up a b p h
  · rw [ite_eq_right h]
    exact coordinate_down a b p h

theorem distance_toNat (a b : U32) :
    (Map.distance a b).toNat = if a.toNat ≤ b.toNat then b.toNat - a.toNat else a.toNat - b.toNat := by
  unfold Map.distance Map.distance_order
  simp only [BitVec.ule_eq_decide, decide_eq_true_eq]
  split
  · rename_i h
    exact BitVec.toNat_sub_of_le h
  · rename_i h
    exact BitVec.toNat_sub_of_le (by change b.toNat ≤ a.toNat; omega)

theorem coordinate_between (a b p : U32) :
    min a.toNat b.toNat ≤ (Map.travel_coordinate a b p).toNat ∧
    (Map.travel_coordinate a b p).toNat ≤ max a.toNat b.toNat := by
  rw [coordinate_toNat]
  have hp := Nat.min_le_right p.toNat (b.toNat - a.toNat)
  have hq := Nat.min_le_right p.toNat (a.toNat - b.toNat)
  by_cases h : a.toNat ≤ b.toNat
  · simp only [ite_eq_left h, Nat.min_eq_left h, Nat.max_eq_right h]
    omega
  · have h' : b.toNat ≤ a.toNat := by omega
    simp only [ite_eq_right h, Nat.min_eq_right h', Nat.max_eq_left h']
    omega

theorem coordinate_step (a b p : U32) :
    (Map.distance a (Map.travel_coordinate a b p)).toNat ≤ p.toNat := by
  rw [distance_toNat, coordinate_toNat]
  have hp := Nat.min_le_left p.toNat (b.toNat - a.toNat)
  have hq := Nat.min_le_left p.toNat (a.toNat - b.toNat)
  have hr := Nat.min_le_right p.toNat (b.toNat - a.toNat)
  have hs := Nat.min_le_right p.toNat (a.toNat - b.toNat)
  split <;> split <;> omega

theorem coordinate_remaining (a b p : U32) :
    (Map.distance (Map.travel_coordinate a b p) b).toNat ≤ (Map.distance a b).toNat := by
  rw [distance_toNat, distance_toNat, coordinate_toNat]
  have hp := Nat.min_le_right p.toNat (b.toNat - a.toNat)
  have hq := Nat.min_le_right p.toNat (a.toNat - b.toNat)
  split <;> split <;> omega

theorem coordinate_close (a b p : U32) (h : (Map.distance a b).toNat ≤ p.toNat) :
    Map.travel_coordinate a b p = b := by
  apply BitVec.eq_of_toNat_eq
  rw [coordinate_toNat]
  rw [distance_toNat] at h
  by_cases hab : a.toNat ≤ b.toNat
  · simp only [ite_eq_left hab] at h ⊢
    rw [Nat.min_eq_right h]
    omega
  · simp only [ite_eq_right hab] at h ⊢
    rw [Nat.min_eq_right h]
    omega

end MotionFacts

theorem coordinate_no_overshoot (start : U32) (target : U32) (pixels : U32) : (((BitVec.ule (min32 start target) (Map.travel_coordinate start target pixels)) && (BitVec.ule (Map.travel_coordinate start target pixels) (max32 start target))) = true) := by
  have bounds := MotionFacts.coordinate_between start target pixels
  simp only [Bool.and_eq_true, BitVec.ule_eq_decide, decide_eq_true_eq]
  unfold min32 max32
  simp only [BitVec.ult_eq_decide, decide_eq_true_eq]
  by_cases h : start.toNat < target.toNat
  · simp only [ite_eq_left h]
    have hle := Nat.le_of_lt h
    simpa only [Nat.min_eq_left hle, Nat.max_eq_right hle] using bounds
  · have hle : target.toNat ≤ start.toNat := by omega
    simp only [ite_eq_right h]
    simpa only [Nat.min_eq_right hle, Nat.max_eq_left hle] using bounds
#print axioms coordinate_no_overshoot

theorem coordinate_distance_nonincreasing (start : U32) (target : U32) (pixels : U32) : ((BitVec.ule (Map.distance (Map.travel_coordinate start target pixels) target) (Map.distance start target)) = true) := by
  simpa only [BitVec.ule_eq_decide, decide_eq_true_eq] using MotionFacts.coordinate_remaining start target pixels
#print axioms coordinate_distance_nonincreasing

theorem coordinate_step_bounded (start : U32) (target : U32) (pixels : U32) : ((BitVec.ule (Map.distance start (Map.travel_coordinate start target pixels)) pixels) = true) := by
  simpa only [BitVec.ule_eq_decide, decide_eq_true_eq] using MotionFacts.coordinate_step start target pixels
#print axioms coordinate_step_bounded

theorem zero_allowance_stationary (start : U32) (target : U32) : ((Map.travel_coordinate start target (0 : U32)) = start) := by
  apply BitVec.eq_of_toNat_eq
  rw [MotionFacts.coordinate_toNat]
  simp
#print axioms zero_allowance_stationary

theorem arrived_coordinate_stationary (target : U32) (pixels : U32) : ((Map.travel_coordinate target target pixels) = target) := by
  apply BitVec.eq_of_toNat_eq
  rw [MotionFacts.coordinate_toNat]
  simp
#print axioms arrived_coordinate_stationary

theorem travel_one_axis (start : Point) (target : Point) : (((eq32 (Point.x (Motion.travel start target)) (Point.x start)) || (eq32 (Point.y (Motion.travel start target)) (Point.y start))) = true) := by
  rcases start with ⟨sx, sy⟩
  rcases target with ⟨tx, ty⟩
  simp only [Motion.travel, eq32, Point.x, Point.y]
  by_cases h : (sx == tx) = true <;> simp only [h, Bool.false_eq_true, ite_true, ite_false, Point.x, Point.y, beq_self_eq_true, Bool.true_or, Bool.or_true]
#print axioms travel_one_axis

theorem travel_step_bounded (start : Point) (target : Point) : (((BitVec.ule (Map.distance (Point.x start) (Point.x (Motion.travel start target))) (4 : U32)) && (BitVec.ule (Map.distance (Point.y start) (Point.y (Motion.travel start target))) (4 : U32))) = true) := by
  rcases start with ⟨sx, sy⟩
  rcases target with ⟨tx, ty⟩
  simp only [Motion.travel, eq32, Point.x, Point.y]
  by_cases h : (sx == tx) = true <;> simp only [h, Bool.false_eq_true, ite_true, ite_false, Point.x, Point.y, Bool.and_eq_true, BitVec.ule_eq_decide, decide_eq_true_eq]
  · constructor
    · simp [MotionFacts.distance_toNat]
    · simpa using MotionFacts.coordinate_step sy ty (4 : U32)
  · constructor
    · simpa using MotionFacts.coordinate_step sx tx (4 : U32)
    · simp [MotionFacts.distance_toNat]
#print axioms travel_step_bounded

theorem travel_distance_nonincreasing (start : Point) (target : Point) : (((BitVec.ule (Map.distance (Point.x (Motion.travel start target)) (Point.x target)) (Map.distance (Point.x start) (Point.x target))) && (BitVec.ule (Map.distance (Point.y (Motion.travel start target)) (Point.y target)) (Map.distance (Point.y start) (Point.y target)))) = true) := by
  rcases start with ⟨sx, sy⟩
  rcases target with ⟨tx, ty⟩
  simp only [Motion.travel, eq32, Point.x, Point.y]
  by_cases h : (sx == tx) = true <;> simp only [h, Bool.false_eq_true, ite_true, ite_false, Point.x, Point.y, Bool.and_eq_true, BitVec.ule_eq_decide, decide_eq_true_eq]
  · constructor
    · exact Nat.le_refl _
    · exact MotionFacts.coordinate_remaining sy ty (4 : U32)
  · constructor
    · exact MotionFacts.coordinate_remaining sx tx (4 : U32)
    · exact Nat.le_refl _
#print axioms travel_distance_nonincreasing

theorem travel_reaches_close_horizontal_target (x : U32) (target : U32) (y : U32) : ((BitVec.ule (Map.distance x target) (4 : U32)) = true) → ((Motion.travel (Point.mk x y) (Point.mk target y)) = (Point.mk target y)) := by
  intro h
  have close := MotionFacts.coordinate_close x target (4 : U32) (by simpa only [BitVec.ule_eq_decide, decide_eq_true_eq] using h)
  have stationary : Map.travel_coordinate y y (4 : U32) = y := by
    apply BitVec.eq_of_toNat_eq
    rw [MotionFacts.coordinate_toNat]
    simp
  simp only [Motion.travel, eq32, Point.x, Point.y]
  by_cases hx : (x == target) = true
  · have equal : x = target := eq_of_beq hx
    simp only [hx, Bool.false_eq_true, ite_true, ite_false, Point.mk.injEq]
    exact ⟨equal, stationary⟩
  · simp only [hx, Bool.false_eq_true, ite_true, ite_false]
    rw [close]
#print axioms travel_reaches_close_horizontal_target
