export declare const PREPARATION_SOURCE_IDENTITY: string;
export declare const SOURCE_IDENTITY: string;
export interface EngineState { $: "Types.State"; canonical: unknown; graphs: unknown; scheduler: unknown; workloads: unknown; random: unknown; advicees: unknown; credentials: unknown; opening: unknown; retiring: unknown; lifecycles: unknown; preparations: unknown; activity_scopes: unknown }
export interface Transition { $: "Transition"; state: EngineState; result: unknown }
export type GraphTransition = { $: "Types.GraphTransition"; state: EngineState; before: unknown; result: unknown } | { $: "Types.GraphRejected"; state: EngineState };
declare const Engine: {
 notice_after(before: EngineState,state: EngineState,scope: unknown,event: unknown,commands: unknown,now: bigint): {state: EngineState; events: unknown};
 notice_exercise(scope: unknown): unknown;
 notice_failure(state: EngineState,scope: unknown,now: bigint,key: bigint,sequence: bigint): unknown;
 notice_lease(state: EngineState,partition: bigint,group: bigint,key: bigint): unknown;
 notice_acknowledge(state: EngineState,partition: bigint,group: bigint,key: bigint): unknown;
 sharing_leave(state: EngineState,scope: unknown): {state: EngineState; events: unknown; valid: unknown};
 sharing_prepare(state: EngineState,scope: unknown,keys: unknown,sizes: unknown): {state: EngineState; routes: unknown; valid: unknown};
 sharing_route(state: EngineState,route: unknown): unknown;
 sharing_routed(state: EngineState,route: unknown,commands: unknown): EngineState;
 sharing_completion(state: EngineState,event: unknown): unknown;
 sharing_binding(state: EngineState,scope: unknown): unknown;
 sharing_result(state: EngineState,evaluation: bigint): unknown;
 freshness_admitted(state: EngineState,scope: unknown,source: unknown,command: unknown): {state: EngineState; source: unknown; actions: unknown};
 freshness_current(state: EngineState,scope: unknown): unknown;
 freshness_checks(state: EngineState,scope: unknown): unknown;
 callback_replaced(state: EngineState,orders: unknown): EngineState;
 callback_owner(state: EngineState, event: unknown): unknown;
 callback_issue(state: EngineState, owner: unknown, order: bigint, at: bigint, action: unknown): EngineState;
 callback_delivered(state: EngineState, order: bigint): EngineState;
 callback_originals(state: EngineState): unknown;
 callback_action(state: EngineState, target: unknown, control: unknown, receipt: unknown, at: bigint, order: bigint): {state: EngineState; result: unknown; cancel: unknown; schedule: unknown};
 activity_event_valid(state: EngineState, event: unknown, partition: bigint, incarnation: bigint): boolean;
 lifecycle_entries(state: EngineState): unknown;
 lifecycle_entry(state: EngineState, partition: bigint): unknown;
 lifecycle_action(state: EngineState, partition: bigint, action: unknown): { state: EngineState; changed: unknown; cleanup: unknown; events: unknown };
 activity_scope(state: EngineState, partition: bigint): unknown;
 activity_valid(state: EngineState, partition: bigint, incarnation: bigint): boolean;
 activity_lifetime(state: EngineState, partition: bigint): number;
 activity_edit(state: EngineState, partition: bigint, incarnation: bigint): { state: EngineState; plan: unknown };
 permit_issue(capture: unknown, now: bigint): unknown;
 permit_issued(capture: unknown, token: bigint): unknown;
 permit_consumed(state: EngineState, command: unknown, partition: bigint, lifetime: bigint): unknown;

 preparation_active(state: EngineState, partition: bigint, lifetime: bigint, round: bigint, operation: bigint): boolean;
 context_credentials(state: EngineState, event: unknown, context: unknown): unknown;
 credential_captured(state: EngineState, operation: bigint): unknown;
 credential_matches(state: EngineState, operation: bigint): boolean;
 callback_matches(event: unknown, target: unknown): boolean;
 issue_actions(state: EngineState, actions: unknown): { state: EngineState; actions: unknown };
 edit_attempt(state: EngineState, partition: bigint, lifetime: bigint): { state: EngineState; plan: unknown };
 scope_event(before: EngineState, after: EngineState, event: unknown, provided: unknown): unknown;
 scope_command(before: EngineState, after: EngineState, command: unknown, provided: unknown): unknown;
 scope_select(bindings: unknown, partition: bigint): unknown;
 intervene_request(state: EngineState, target: unknown, outcome: unknown, delay: bigint): unknown;
 declare_advicee(state: EngineState, identity: bigint, seed: number): { state: EngineState; scope: unknown; valid: boolean };
 advicee_identity(state: EngineState, identity: bigint): unknown;
 advicee_partition(state: EngineState, partition: bigint): unknown;
 advicee_targets(state: EngineState, identity: unknown): unknown;
 credentials(state: EngineState): unknown;
 configure_credentials(state: EngineState, available: boolean, generation: bigint): EngineState;
 credential_action(state: EngineState, available: boolean, rotation: boolean): EngineState;
 generate_tree(seed: bigint, operation: bigint, unit: bigint, profile: unknown, limits: unknown): unknown;
 session_delay(settings: unknown, random: number): number;
 clock(state: EngineState): number;
 configure_seed(state: EngineState, seed: bigint): EngineState;
 configure_workload(state: EngineState, partition: bigint, profile: unknown): EngineState;
 workload_action(state: EngineState, partition: bigint, action: unknown): { state: EngineState; events: unknown; valid: boolean };
 workload_valid(state: EngineState, partition: bigint, generation: bigint, recurring: boolean): boolean;
 workload_duration(state: EngineState, partition: bigint, fallback: bigint): number;
 pre_timing(state: EngineState, partition: bigint, provided: unknown, fallback: bigint, lifetime: bigint): unknown;
 sample_outcome(state: EngineState, weights: unknown): { state: EngineState; outcome: number };
 /** Positive sampler-domain binary64: finite sum <=600; no overflow/NaN. */
 numeric_add(a: unknown, b: unknown): unknown;
 /** Positive total, operands <=600 and ratio <=1 (subnormals included). */
 numeric_divide(a: unknown, b: unknown): unknown;
 random_initial(seed: bigint): number;
 random_sample(random: number, weights: unknown): { random: number; outcome: number };
 session_initial(settings: unknown, seed: number, codes: unknown, bytes: bigint, units: unknown): unknown;
 session_next(settings: unknown, stream: unknown): unknown;
 session_generation(stream: unknown): number;
 session_sizes(stream: unknown, bytes: bigint, units: unknown): unknown;
 session_burst(count: bigint, stream: unknown): unknown;
 session_interval(settings: unknown, interval: number): unknown;
 session_rewind(settings: unknown, stream: unknown): unknown;
 session_suspend(settings: unknown, stream: unknown, suspended: boolean): unknown;
 session_finish(stream: unknown, continuation: boolean): unknown;
 session_advice(settings: unknown, stream: unknown): unknown;
 enqueue(state: EngineState, at: bigint, order: bigint): EngineState;
 take(state: EngineState): { state: EngineState; entry: unknown };
 queued(state: EngineState): unknown;
 cancel(state: EngineState, order: bigint): EngineState;
 initial(limits: unknown): EngineState;
 canonical(state: EngineState): unknown;
 step(state: EngineState, event: unknown): Transition;
 graph_step(state: EngineState, key: unknown, position: bigint, limits: unknown, event: unknown): GraphTransition;
 revalidate(state: EngineState, context: unknown): unknown;
 fence(state: EngineState, event: unknown, generated: boolean, context: unknown): unknown;
 after(before: EngineState, state: EngineState, event: unknown): unknown;
 edit(state: EngineState, partition: bigint, lifetime: bigint): unknown;
 preparation_fact_time(delay: bigint, index: bigint, count: bigint): bigint;
 preparation_completed(partition: bigint, lifetime: bigint, round: bigint, operation: bigint, units: unknown, delay: bigint): unknown;
 handle(state: EngineState, event: unknown, command: unknown, context: unknown): unknown;
};
export default Engine;
