import { REVIEW_FEEDBACK_HEADING, REVIEW_FEEDBACK_INSTRUCTIONS } from "../feedback/message.ts";
type Stats = { readonly status: "stats"; readonly queued: number; readonly running: number; readonly pendingAdvice: number; readonly pendingFindingBatches: number; readonly pendingOperationalNotices: number; readonly pendingEvaluations: number; readonly successfulCacheEntries: number };
export type HostOutputKind = "none" | "invalid" | "findings" | "operational-notice" | "findings-and-operational-notice";
const record = (value: unknown): Readonly<Record<string, unknown>> | undefined => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Readonly<Record<string, unknown>> : undefined;
export const classifyHookOutput = (value: unknown): HostOutputKind => {
  const output = record(value); const hook = record(output?.hookSpecificOutput);
  if (hook === undefined) return Object.keys(output ?? {}).length === 0 ? "none" : "invalid";
  if (hook.hookEventName !== "PostToolUse" || typeof hook.additionalContext !== "string") return "invalid";
  const lines = hook.additionalContext.split("\n").filter((line) => line.length > 0);
  if (lines[0] !== REVIEW_FEEDBACK_HEADING) return "invalid";
  const body = lines.slice(1).filter(line => line !== REVIEW_FEEDBACK_INSTRUCTIONS); const notices = body.filter((line) => line.startsWith("Operational notice:")); const findings = body.length - notices.length;
  if (findings > 0 && notices.length > 0) return "findings-and-operational-notice";
  if (findings > 0) return "findings";
  if (notices.length > 0) return "operational-notice";
  return "invalid";
};
export const classifyLiveOutcome = (input: { readonly admissionExitCode: number | null; readonly hostOutputKind: HostOutputKind; readonly stats: Stats | undefined }) => {
  if (input.admissionExitCode !== 0) return { contractOutcome: "admission-failed", successfulEvaluation: false } as const;
  const terminal = input.stats;
  if (terminal === undefined) return { contractOutcome: "completion-unobserved", successfulEvaluation: false } as const;
  if (terminal.queued > 0 || terminal.running > 0 || terminal.pendingEvaluations > 0) return { contractOutcome: "delayed-completion-unobserved", successfulEvaluation: false } as const;
  if (terminal.successfulCacheEntries !== 1) return { contractOutcome: input.hostOutputKind === "operational-notice" ? "operational-failure-notice-attempted-unacknowledged" : terminal.pendingOperationalNotices > 0 ? "operational-failure-notice-pending" : "evaluation-failed-or-unobserved", successfulEvaluation: false } as const;
  if (input.hostOutputKind === "findings") return { contractOutcome: "completed-findings-output-attempted-unacknowledged", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "findings-and-operational-notice") return { contractOutcome: "completed-findings-and-operational-notice-attempted-unacknowledged", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "operational-notice") return { contractOutcome: "completed-clear-with-operational-notice-attempted-unacknowledged", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "none" && terminal.pendingFindingBatches > 0 && terminal.pendingOperationalNotices > 0) return { contractOutcome: "completed-findings-and-operational-notice-pending", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "none" && terminal.pendingFindingBatches > 0) return { contractOutcome: "completed-findings-pending", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "none" && terminal.pendingOperationalNotices > 0) return { contractOutcome: "completed-clear-operational-notice-pending", successfulEvaluation: true } as const;
  if (input.hostOutputKind === "none" && terminal.pendingAdvice === 0) return { contractOutcome: "completed-clear-no-advice", successfulEvaluation: true } as const;
  return { contractOutcome: "successful-evaluation-output-unclassified", successfulEvaluation: true } as const;
};
