// Preserve the deterministic boundary/proof inventory independently of CLI routing.
export const qualityPreflight = [
  "quality-preflight",
  "--test",
  "scripts/test-harness/run-checks.test.mjs",
  "scripts/test-harness/immediate-errors.test.mjs",
  "scripts/test-harness/verification-plan.test.mjs",
  "scripts/test-harness/verify.test.mjs",
  "scripts/test-harness/check-complexity.test.mjs",
  "scripts/test-harness/standalone-environment.test.mjs"
]
export const precheckStages = [
  qualityPreflight,
  ["documentation", "scripts/generate-documentation.mjs", "--check"],
  ["bend-generation", "scripts/build-bend-producers.mjs"],
  ["bend-artifacts", "scripts/verify-bend-artifacts.mjs"],
  ["canonical-authority", "scripts/check-canonical-authority.mjs"],
  ["jev-request", "--experimental-strip-types", "packages/agent-flow-bend/scripts/check-jev-request.mjs"],
  ...[
    "production-authority",
    "capacity-boundary",
    "permit-boundary",
    "review-boundary",
    "dispatch-boundary",
    "stop-boundary",
    "collection-boundary",
    "delivery-boundary",
    "revision-boundary",
    "response-authority-boundary",
    "reuse-boundary",
    "notice-boundary",
    "retention-boundary",
    "configuration-boundary",
    "file-eligibility-boundary",
    "rule-boundary"
  ].map((name) => [name, `scripts/check-${name}.mjs`]),
  ["bend-progress", "packages/agent-flow-bend/scripts/check-progress.mjs"],
  ["content-isolation", "packages/agent-flow-bend/scripts/check-content-isolation.mjs"],
  ["content-wire-mutants", "scripts/check-content-wire-mutants.mjs"],
  [
    "native-pi-observation",
    "--test",
    "scripts/native-pi-observation.test.mjs",
    "scripts/native-pi-package-assets.test.mjs",
    "scripts/native-claude-package.test.mjs"
  ],
  ["native-rule-observation", "--test", "scripts/native-rule-observation.test.mjs"],
  [
    "verification-infrastructure",
    "--test",
    "--test-concurrency=1",
    "scripts/artifact-store.test.mjs",
    "scripts/dev-pack.test.mjs",
    "scripts/dev-install.test.mjs",
    "scripts/archive-inventory.test.mjs",
    "scripts/install-git-hooks.test.mjs",
    "scripts/pinned-bun.test.mjs",
    "scripts/pinned-typescript.test.mjs",
    "scripts/compiler-selection.test.mjs",
    "scripts/generate-release-identity.test.mjs",
    "scripts/bend-toolchain.test.mjs",
    "scripts/native-bindings.test.mjs",
    "scripts/native-pi-preflight.test.mjs",
    "scripts/native-process.test.mjs",
    "scripts/test-harness/bun-coverage.test.mjs"
  ],
  [
    "build-workflow",
    "--test",
    "--test-concurrency=1",
    "scripts/package-graph.test.mjs",
    "scripts/check-development-imports.test.mjs",
    "scripts/check-compiler-receipts.test.mjs",
    "scripts/compiler-evidence.test.mjs",
    "scripts/clean-compiler-output.test.mjs",
    "scripts/check-workspace-imports.test.mjs",
    "scripts/source-type-evidence.test.mjs",
    "scripts/assembly-context.test.mjs",
    "scripts/bend-producer.test.mjs",
    "scripts/generate-bend-base-evidence.test.mjs",
    "scripts/hook-import-boundary.test.mjs",
    "scripts/source-loader-policy.test.mjs",
    "scripts/source-analysis-receipt.test.mjs",
    "scripts/build-contributions.test.mjs",
    "scripts/check-assembly-receipt.test.mjs",
    "scripts/assembly-prerequisites.test.mjs",
    "scripts/assemble-entry.test.mjs",
    "scripts/assemble-host-modules.test.mjs",
    "scripts/check-build-boundaries.test.mjs",
    "scripts/authored-task-inputs.test.mjs",
    "scripts/generate-turbo-config.test.mjs",
    "scripts/release-assets.test.mjs",
    "scripts/audit-release-tarball.test.mjs",
    "scripts/release-archive.test.mjs",
    "scripts/native-artifact.test.mjs",
    "scripts/host-module-imports.test.mjs",
    "scripts/external-loader-profile.test.mjs",
    "scripts/external-runtime-evidence.test.mjs",
    "scripts/host-module-graph.test.mjs",
    "scripts/host-module-plan.test.mjs",
    "scripts/publish-product.test.mjs",
    "scripts/owned-lock.test.mjs",
    "scripts/build-lock.test.mjs",
    "scripts/build-process.test.mjs",
    "scripts/build-ownership.test.mjs",
    "scripts/native-compiler-inputs.test.mjs",
    "scripts/native-linker-inputs.test.mjs",
    "scripts/native-toolchain-inputs.test.mjs",
    "scripts/native-task-receipt.test.mjs",
    "scripts/native-task.test.mjs",
    "scripts/native-task-inputs.test.mjs",
    "scripts/native-header-search.test.mjs",
    "scripts/build-watch-coordinator.test.mjs",
    "scripts/build-watch-observation.test.mjs",
    "scripts/build-workflow-acceptance.test.mjs",
    "scripts/build-resolution-acceptance-cases.test.mjs",
    "scripts/measure-hook-startup-commands.test.mjs",
    "scripts/check-runtime-clock.test.mjs",
    "scripts/measure-hook-startup-summary.test.mjs"
  ],
  ["test-harness", "--test", "scripts/test-harness/prepare-archive.test.mjs"]
]
