/** Source-free update decisions. Native arrays and proposal identities stay in the host. */
export type UpdatePhase = { readonly $: "UpdateDiscovering" | "UpdateTargeting" | "UpdatePreviewing" | "UpdateReview" | "UpdateApproval" | "UpdateApplying" | "UpdateActivating" | "UpdateDone" | "UpdateCancelled" }
export type UpdatePatch = {readonly $: "UpdateNoPatch" | "UpdateDiscoveredPatch" | "UpdatePreviewProposalPatch" | "UpdatePreviewOutcomePatch" | "UpdateCurrentPreviewPatch" | "UpdateSkippedPatch" | "UpdateBeginApplyPatch" | "UpdateObservedApplyPatch" | "UpdateObservedActivatePatch" | "UpdateActivatedPreviewPatch" | "UpdateActivatedApplyPatch"}
export type UpdatePlan = {readonly $: "UpdateHold"} | {readonly $: "UpdateAdvance"; readonly phase: UpdatePhase; readonly patch: UpdatePatch}
export type UpdateAxis = "unique" | "nonempty" | "matched" | "validDigest" | "more" | "proposals" | "pending" | "approvalsMatch" | "yes" | "returnPreview"
export declare const updateRoutes: readonly {readonly axes: readonly {readonly name: UpdateAxis; readonly radix: number}[]; readonly plans: readonly UpdatePlan[]}[]
export declare const updateNavigationTable: Readonly<Record<string,Readonly<Record<string,number | Readonly<Record<string,number>>>>>>
export type UpdateNativeCommand<Host extends string> = {readonly kind:"discover"|"target"; readonly id:number} | {readonly kind:"preview"|"activate"; readonly id:number;readonly host:Host} | {readonly kind:"apply";readonly id:number;readonly host:Host;readonly digest:string}
export declare const updateNativeCommand: <Host extends string>(model:{readonly phase:string;readonly revision:number;readonly cursor:number;readonly agents:readonly {readonly host:Host;readonly digest?:string}[]})=>UpdateNativeCommand<Host>|undefined
export type UpdatePatchName = "no" | "discovered" | "previewProposal" | "previewOutcome" | "currentPreview" | "skipped" | "beginApply" | "observedApply" | "observedActivate" | "activatedPreview" | "activatedApply"
export declare const updateBindReducers: <Model extends {readonly phase:string},Action extends {readonly kind:string}>(facts:Readonly<Record<UpdateAxis,(model:Model,action:Action)=>number>>,readTag:(action:Action)=>string|undefined,apply:Readonly<Record<UpdatePatchName,(model:Model,action:Action,phase:"Discovering"|"Targeting"|"Previewing"|"Review"|"Approval"|"Applying"|"Activating"|"Done"|"Cancelled")=>Model>>)=>(model:Model,action:Action)=>Model
